name: DevOps-GithubActions
on: push
jobs: 
    #build job
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
            - name: Install Dependencies
              run: npm install
            - name: Build project  // this seems to be referred to as artifact
              run: npm run build
            - name: Upload artifact to enable deployment
              uses: actions/upload-artifact@v3
              with:
                name: production-files
                path: ./dist
    # Deploy job
    deploy:
        # Add a dependency to the build job
        needs: build
        # Specify the runner + deployment step
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                name: production-files
                path: ./dist
            - name: Deploy to github pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                # this token is the secret that we set up and allows github pages to deploy our application
                github_token: ${{ secrets.CICD_TEST_TOKEN }}
                publish_dir: ./dist
